package components.editors

/**
 * By courtesy of @slivver | Sylvan (854115910625263616) of SwissRPG's Discord Server
 */
val gameSystems = arrayOf(
    "13th Age",
    "7th Sea",
    "A Christmas Belonging",
    "A Fitsfull of Darkness",
    "A Long Walk Home",
    "A Nocturne",
    "A Quiet Year",
    "A Slate",
    "A Torch in the Dark",
    "A Witch, A Gallows Bird",
    "Adrenaline",
    "Adventure Skeletons",
    "Adventure!",
    "Aethernet",
    "Afraid of the Dark",
    "Against the Wind",
    "Alas for the Awful Sea",
    "Alice is Missing",
    "Alien the TTRPG",
    "All That I Am",
    "Alone Among the Stars",
    "Amber Diceless",
    "Amongst the Stars",
    "And the Gunslinger Followed",
    "Andor",
    "ANGEL: NeuEon",
    "Anima: Beyond Fantasy",
    "Apocalypse Frame",
    "Apocalypse Keys",
    "Apocalypse World",
    "Arkham Horror the TTRPG",
    "Arudin",
    "Ashen Stars",
    "Asphalt & Trouble",
    "Avatar Legends",
    "Band of Blades",
    "Basic Fantasy",
    "Basic Roleplaying",
    "Battletech",
    "Beach Patrol",
    "Beacon",
    "Beam Saber",
    "Beyond the Wall",
    "Big Eyes, Small Mouth",
    "Blade Runner the TTRPG",
    "Blades in the Dark",
    "Bloodstone",
    "Bloody Demon Slayers",
    "Blue Planet: Recontact",
    "Bluebeards Bride",
    "Book of Unremitting Horror",
    "Boot Hill",
    "Brindlewood Bay",
    "Brinkwood",
    "Broken Compass",
    "Bubblegumshoe",
    "Bump in the Dark",
    "Cain",
    "Cairn",
    "Call of Cthulhu",
    "Camp Peasant",
    "Candela Obscura",
    "Castle Frankenstein",
    "Castle of Memories",
    "Castles & Crusades",
    "Cats of Catthulhu",
    "Champions",
    "Chivalry & Sorcery",
    "City of Mist",
    "Copperhead County",
    "Coriolis",
    "Court of Blades",
    "Coyote & Crow",
    "Crash Cart",
    "Crash Pandas",
    "Crecent Moon",
    "Critical Core",
    "Crucible",
    "Cthulhu Confidential",
    "Cyber + Punk",
    "Cyberpunk",
    "Darkness of the Demimonde",
    "Dead of Night",
    "Deadlands",
    "Deadly Revelation",
    "Death in Space",
    "Definitely Wizards",
    "Delta Green",
    "Demigods",
    "Demon City",
    "Den of Wolves",
    "Dethrone the Divine",
    "Die",
    "Divine Blood",
    "Doctor Who",
    "Dogs in the Vineyard",
    "Dolls of Theseus",
    "Dragon Age",
    "Dragon Warriors",
    "Dragonbane",
    "Draw Steel",
    "Dread",
    "Dresden Files",
    "Dune: Adventures in the Imperium",
    "Dungeon Crawl Classics",
    "Dungeon World",
    "Dungeons & Dragons",
    "Eat the Reich",
    "Eclipse Phase",
    "Electric Bastionland",
    "Empty Table",
    "Entombed",
    "Epitaph",
    "Epyllion",
    "Errante",
    "Everyone is John",
    "Everywhen",
    "Exacorps",
    "Exalted",
    "Ex Novo",
    "External Containment Bureau",
    "Eyes on the Prize",
    "EZ D6",
    "Fabula Ultima",
    "Fall of Delta Green",
    "Fall of Magic",
    "Fallout",
    "Fantasy World",
    "Fast Fantasy",
    "FATE",
    "Fear Itself",
    "Feathers",
    "Fellowship",
    "Feng Shui",
    "FHTAGN",
    "Fiasco",
    "Fighting Delivery Felines",
    "FIST: Ultra Edition",
    "Forbidden Lands",
    "Four Against Darkness",
    "Gamma World",
    "Gang Busters",
    "Girl by Moonlight",
    "Glitter Hearts",
    "Goblin Slayer",
    "Godeater",
    "Golden Sky Stories",
    "Guardians of Aimsir",
    "GURPS",
    "Haven Ae",
    "Heckin' Good Doggos",
    "Hellborn",
    "Het Tijdschrift",
    "Hollow Earth Expedition",
    "Honey Heist",
    "Household",
    "How to Be a Hero",
    "How We Learned to Fill our Lungs with Salt",
    "Hunter: The Reckoning",
    "Hyperborea",
    "I Went to Bourbon, Indiana Once",
    "Index Card RPG",
    "Inspirisles",
    "Into the Glacier",
    "Into the Odd",
    "Ironsworn",
    "Itras By",
    "Judge Dredd",
    "Jukebox",
    "Keepers of Antarra",
    "Kingdom",
    "Kitten Witches",
    "Knave",
    "Konosuba: Gods Blessing on This Wonderful World!",
    "Kult: Divinity Lost",
    "Lady Blackbird",
    "Lamentations of the Flame Princess",
    "Lamplighter's Festival",
    "Lancer",
    "Legacy",
    "Legend in the Mist",
    "Legend of the Five Rings",
    "Lex Occultum",
    "Lichoma",
    "Liminal Horror",
    "Little Wizards",
    "Lo! Thy Dread Empire",
    "Lordsworn",
    "Low Fantasy Gaming",
    "Mage: The Ascention",
    "Maharlika",
    "Major Magica",
    "Marvel Multiverse TTRPG",
    "MASHED",
    "Masks: A New Generation",
    "Maskwitches of Forgotten Doggerland",
    "Mausritter",
    "Mech Warrior",
    "Mesopotamians",
    "Meta",
    "Minutes to Midnight",
    "Mircalla's Fantasy",
    "Mistborn Adventure Game",
    "Momento Mori",
    "Monster of the Week",
    "Monsterhearts",
    "Monty Python's Cocurricular Mediaeval Reenactment Programme",
    "Mörk Borg",
    "Mothership",
    "Mountain Home",
    "Mourn",
    "Mutant: Year Zero",
    "Mutant City Blues",
    "Mutants & Masterminds",
    "Mythic",
    "Mythic Iceland",
    "Nahual",
    "Nasty, Brutish & Long",
    "Neon City Overdrive",
    "Neon Nighs",
    "Neon Sundown",
    "NETWORK 23",
    "Never Going Home",
    "Nibiru",
    "Night's Black Agents",
    "Numenera",
    "Numbskulls",
    "Old School Essentials",
    "Orbital Blues",
    "Outgunned",
    "Paranioa",
    "Pasión de las Pasiones",
    "Pathfinder",
    "Pendragon",
    "Penumbra City",
    "Pine Shallows",
    "Posthuman Saga",
    "Quest",
    "R'Lyehwatch",
    "Rebel Crown",
    "Rebels of the Outlaw Wastes",
    "Reign",
    "Relics - A Game of Angels",
    "Return to Wonderland",
    "Righteous Blood Ruthless Blades",
    "Rings and Running Stones",
    "Risus",
    "Rocket Age",
    "Roll for Shoes",
    "Root RPG",
    "Rosewood Abbey",
    "Ruma – Dawn of Empire",
    "Runecairn",
    "RuneQuest",
    "Runners in th Shadows",
    "Ryuutama",
    "Savage Worlds",
    "Second Sun",
    "Scarlet Heroes",
    "Scum and Villainy",
    "Sea of Dead Men",
    "Shadow of the Demon Lord",
    "ShadowDark",
    "Shadowrun",
    "Shinobigami",
    "Skeletons",
    "Slugblaster",
    "Solo Game Master’s Guide",
    "Songbirds",
    "Songs for the Dusk",
    "Space Gothic",
    "Spirit of 77",
    "Spirit of the Century",
    "Sprouts",
    "Spycraft",
    "Star Frontiers",
    "Star Trek Adventures",
    "Star Wars the TTRPG",
    "Starfinder",
    "Stargate the TTRPG",
    "Stars Without Number",
    "Stormbringer",
    "Swords of the Serpentine",
    "Sword World",
    "Symbaroum",
    "Tales from the Floating Vagabond",
    "Tales from the Loop",
    "Tales of Equestria",
    "Tales of the Valiant",
    "Tales of Xadia",
    "Teachers and Tentacles",
    "Teeth and Steel",
    "Ten Candles",
    "Tenra Bansho Zero",
    "The Black Cat",
    "The Black Hack",
    "The Black Sword Hack",
    "The Burning Wheel",
    "The Chronicles of Darkness",
    "The Dark Eye",
    "The Day After Ragnarok",
    "The Electrum Archive",
    "The Entombed Crown",
    "The Esoterrorists",
    "The Everlasting",
    "The Gaean Reach",
    "The Gas Station",
    "The League of Extraordinary Gentlemen",
    "The Life-Saving Magic of Inventorying",
    "The Lord of the Rings the TTRPG",
    "The Magnus Archives",
    "The Midnight World",
    "The One Ring",
    "The Riddle of Steel",
    "The Shadow of Yesterday",
    "The Sprawl",
    "The Troubleshooters",
    "The Walking Dead Universe TTRPG",
    "The Warren",
    "The Weird",
    "The Wheel of Time",
    "The Wicked Sisters",
    "The Wildsea",
    "The Witch is Dead",
    "The Wretched",
    "The Yellow King",
    "Their Blood is the Sea",
    "Things from the Flood",
    "Thirsty Sword Lesbians",
    "This Mortal Coil",
    "Tiny Cthulhu",
    "Tiny Dungeon",
    "Tiny Frontiers",
    "Tiny Frontiers Mecha Monsters",
    "Tiny Gods",
    "Tiny Gunslingers",
    "Tiny Living Dead",
    "Tiny Pirates",
    "Tiny Taverns",
    "Tiny Wastelands",
    "Top Secret",
    "Torg",
    "Trash Pals",
    "Traveller",
    "Trial of Cthulhu",
    "Triangle Agency",
    "Trinity",
    "Troika!",
    "Trophy",
    "Trophy Dark",
    "Tunnel Goons",
    "Tunnels and Trolls",
    "TWERPS",
    "Two-Fisted Tales",
    "Ultra Violet Grasslands",
    "Urban Shadows",
    "Vaesen",
    "Vampire: The Masquerade",
    "Vaults of Vaarn",
    "Vergence",
    "Visigoths vs Mall Goths",
    "Wanderhome",
    "Warhammer",
    "We Die Here",
    "Werewolf: The Apocalypse",
    "Whitehack",
    "Wickedness",
    "World Wide Wrestling RPG",
    "Würm",
    "Wushu",
    "You and I at the End of the World",
    "Zombie World"
)